USE emprestimos;

DROP PROCEDURE IF EXISTS cobra_taxa;

DELIMITER //
CREATE PROCEDURE cobra_taxa(IN taxa DECIMAL(30, 2))
BEGIN
	SET @OLD_SQL_SAFE_UPDATES = @@SQL_SAFE_UPDATES;
	SET SQL_SAFE_UPDATES=0;
	UPDATE usuario SET saldo = IF(saldo > taxa, saldo - taxa, 0.0);
	SET SQL_SAFE_UPDATES=@OLD_SQL_SAFE_UPDATES;
END//
DELIMITER ;
